spring:
  application:
    name: ai-trading-assistant

  profiles:
    active: local

  data:
    redis:
      host: localhost
      port: 6379

  management:

    endpoints:
      web:
        exposure:
          include: health,info,metrics,env,beans,mappings

    endpoint:
      health:
        show-details: always

    info:
      env:
        enabled: true

  info:
    app:
      name: AI Trading Assistant
      description: AI Powered Stock Trading Backend
      version: 1.0.0
      developer: Deepak Rathore
      company: Personal Project

jwt:
  secret: VGVzdFNwcmluZ0Jvb3RKV1RTZWNyZXRLZXlGb3JEZW1vMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
  expiration: 86400000

