spring:
  application:
    name: ai-trading-assistant

  profiles:
    active: local

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: VGVzdFNwcmluZ0Jvb3RKV1RTZWNyZXRLZXlGb3JEZW1vMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
  expiration: 86400000